"""
AIForge Builder
===============

Consumes a validated planner result and writes a complete, runnable AI project
to disk.  The Builder is the single source of truth for what gets generated.

Design rules
------------
* NEVER generate working code for catalog-only components — they get honest
  stubs that explain their status and what is needed to activate them.
* Executable components (text_classifier, fastapi) get real, working code.
* The generated project is self-contained: requirements.txt + Dockerfile are
  included so it can be shipped and run immediately once model artifacts exist.
* pipeline.py implements a real Component/Pipeline abstraction (not a stub).
  Each step calls its component's run() method; non-executable components raise
  NotImplementedError with a clear message.
* The generated server.py wires the trained model.joblib when text_classifier
  is in the pipeline; otherwise it returns a structured "not_implemented" response.
"""
from __future__ import annotations

import json
import re
import time
import uuid
from pathlib import Path
from textwrap import dedent
from typing import Any

from app.planner import REGISTRY, analyze_spec

# Where generated projects land (relative to this file → backend/generated_projects/)
_BASE_DIR = Path(__file__).resolve().parents[1]
GENERATED_DIR = _BASE_DIR / "generated_projects"
GENERATED_DIR.mkdir(exist_ok=True)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _slugify(value: str) -> str:
    value = re.sub(r"[^a-zA-Z0-9_-]+", "-", value.strip().lower())
    return value.strip("-") or "aiforge-project"


def _execution_status(plan: dict[str, Any]) -> str:
    """
    "ready"   — every runtime component is executable now
    "partial" — pipeline contains catalog/config-required components
    "blocked" — no executable component at all (edge case)
    """
    selected = plan.get("selected_components", [])
    runtime = [c for c in selected if c != "fastapi"]
    if not runtime:
        return "blocked"
    exec_ids = {cid for cid in runtime if REGISTRY.get(cid, {}).get("executable", False)}
    if not exec_ids:
        return "blocked"
    if len(exec_ids) == len(runtime):
        return "ready"
    return "partial"


# ---------------------------------------------------------------------------
# File generators
# ---------------------------------------------------------------------------

def _make_readme(project_name: str, spec: str, plan: dict[str, Any]) -> str:
    selected = plan.get("selected_components", [])
    exec_status = _execution_status(plan)
    exec_label = {"ready": "✅ Fully executable", "partial": "⚠️ Partial — catalog components require future activation", "blocked": "❌ Blocked — no executable components"}.get(exec_status, exec_status)

    lines = [
        f"# {project_name}",
        "",
        "> Generated by **AIForge** from a natural-language specification.",
        "",
        "## Specification",
        "",
        spec,
        "",
        f"## Execution status: {exec_label}",
        "",
        "## Pipeline components",
        "",
    ]
    for step in plan.get("pipeline_steps", []):
        icon = "✅" if step.get("executable") else "🔵"
        tag = "MVP ready" if step.get("executable") else "Catalog — not yet executable"
        lines.append(f"{step['order']}. {icon} **{step['name']}** — {tag}")
        if step.get("reason"):
            lines.append(f"   - _{step['reason']}_")
    lines += [
        "",
        "## Quick start",
        "",
        "```bash",
        "pip install -r requirements.txt",
        "uvicorn agent.server:app --host 0.0.0.0 --port 8000",
        "```",
        "",
        "## Training (text classifier)",
        "",
        "```bash",
        "# POST a labeled CSV to the AIForge training endpoint",
        "curl -X POST 'http://localhost:8000/api/train?project_id=<project_id>' \\",
        "     -F 'dataset=@your_data.csv'",
        "```",
        "",
        "## Prediction",
        "",
        "```bash",
        'curl -X POST http://localhost:8000/predict \\',
        '     -H "Content-Type: application/json" \\',
        '     -d \'{"text": "Your input text here"}\'',
        "```",
        "",
        "---",
        "",
        "*AIForge MVP — catalog components will be activated in future phases.*",
    ]
    return "\n".join(lines) + "\n"


def _make_requirements(plan: dict[str, Any]) -> str:
    """
    Always include the executable core.  Add notes for catalog components.
    """
    selected = plan.get("selected_components", [])
    has_opencv = "opencv" in selected and REGISTRY.get("opencv", {}).get("executable", False)
    has_ocr = "ocr" in selected and REGISTRY.get("ocr", {}).get("executable", False)

    pkgs = [
        "# Core serving",
        "fastapi>=0.115",
        "uvicorn[standard]>=0.34",
        "python-multipart>=0.0.9",
        "",
    ]
    if "text_classifier" in selected:
        pkgs += [
            "# Text classification (executable)",
            "scikit-learn>=1.5",
            "joblib>=1.4",
            "pandas>=2.2",
            "",
        ]
    if has_opencv:
        pkgs += [
            "# Vision preprocessing (executable)",
            "opencv-python-headless>=4.9",
            "Pillow>=10.0",
            "numpy>=1.24",
            "",
        ]
    if has_ocr:
        pkgs += [
            "# OCR (executable — requires Tesseract system binary)",
            "# Install: https://github.com/UB-Mannheim/tesseract/wiki",
            "pytesseract>=0.3",
            "",
        ]
    catalog_in_plan = [
        c for c in selected
        if not REGISTRY.get(c, {}).get("executable", False) and c not in ("fastapi",)
    ]
    if catalog_in_plan:
        pkgs += [
            "# Catalog components — packages listed for reference only.",
            "# These components are not yet executable in the AIForge MVP.",
            "# Uncomment and install when you activate them.",
        ]
        for cid in catalog_in_plan:
            comp = REGISTRY.get(cid, {})
            name = comp.get("name", cid)
            if comp.get("requires_system_binary"):
                guide = comp.get("install_guide", "see AIForge docs")
                pkgs.append(f"# {name}: requires system binary — {guide}")
            else:
                pkgs.append(f"# {name}: see AIForge docs for activation instructions")
        pkgs.append("")
    pkgs += ["# Testing", "pytest>=8.3", "httpx>=0.27"]
    return "\n".join(pkgs) + "\n"


def _make_dockerfile(plan: dict[str, Any]) -> str:
    selected = plan.get("selected_components", [])
    has_opencv = "opencv" in selected and REGISTRY.get("opencv", {}).get("executable", False)
    has_ocr = "ocr" in selected and REGISTRY.get("ocr", {}).get("executable", False)

    pip_pkgs = ["fastapi", "uvicorn[standard]", "python-multipart"]
    if "text_classifier" in selected:
        pip_pkgs += ["scikit-learn", "joblib", "pandas"]
    if has_opencv:
        pip_pkgs += ["opencv-python-headless", "Pillow", "numpy"]
    if has_ocr:
        pip_pkgs.append("pytesseract")

    pip_line = " ".join(pip_pkgs)

    ocr_note = ""
    if has_ocr:
        ocr_note = (
            "# Install Tesseract OCR system binary\n"
            "RUN apt-get update && apt-get install -y tesseract-ocr && rm -rf /var/lib/apt/lists/*\n"
        )

    return dedent(f"""\
        FROM python:3.12-slim
        WORKDIR /app
        COPY requirements.txt /app/
        {ocr_note}RUN pip install --no-cache-dir {pip_line}
        COPY . /app/
        EXPOSE 8000
        CMD ["uvicorn", "agent.server:app", "--host", "0.0.0.0", "--port", "8000"]
    """)


def _make_pipeline_json(project_id: str, project_name: str, spec: str, plan: dict[str, Any]) -> str:
    return json.dumps(
        {
            "project_id": project_id,
            "project_name": project_name,
            "specification": spec,
            "generated_at": time.time(),
            "execution_status": _execution_status(plan),
            "execution_ready": plan.get("execution_ready", False),
            "input": plan.get("input", {}),
            "selected_components": plan.get("selected_components", []),
            "implemented_components": plan.get("implemented_components", []),
            "catalog_components": plan.get("catalog_components", []),
            "pipeline_steps": plan.get("pipeline_steps", []),
            "warnings": plan.get("warnings", []),
        },
        indent=2,
    )


def _make_project_json(
    project_id: str,
    project_name: str,
    spec: str,
    plan: dict[str, Any],
    generated_files: list[str],
) -> str:
    return json.dumps(
        {
            "project_id": project_id,
            "project_name": project_name,
            "specification": spec,
            "created_at": time.time(),
            "status": "generated",
            "execution_status": _execution_status(plan),
            "execution_ready": plan.get("execution_ready", False),
            "components": [c["name"] for c in plan.get("components", [])],
            "executable_components": plan.get("implemented_components", []),
            "catalog_components": plan.get("catalog_components", []),
            "warnings": plan.get("warnings", []),
            "generated_files": generated_files,
        },
        indent=2,
    )


# ---------------------------------------------------------------------------
# pipeline.py — real component abstraction
# ---------------------------------------------------------------------------

def _make_pipeline_py(plan: dict[str, Any]) -> str:
    """
    Generates a pipeline.py with a real Component base class and one
    concrete subclass per selected component.

    Executable components get real run() logic.
    Catalog components get an honest stub that raises NotImplementedError.
    """
    selected = plan.get("selected_components", [])
    steps = plan.get("pipeline_steps", [])

    # Build per-component class bodies
    class_blocks: list[str] = []
    for step in steps:
        cid = step["id"]
        name = step["name"]
        executable = step.get("executable", False)
        deps = step.get("dependencies", [])
        dep_str = ", ".join(deps) if deps else "none"

        if cid == "opencv":
            class_blocks.append(dedent('''\
                class OpencvComponent(Component):
                    """Executable: OpenCV image preprocessing (grayscale, denoise, binarise)."""

                    name = "opencv"

                    def run(self, context: dict) -> dict:
                        image_bytes = context.get("image_bytes")
                        if image_bytes is None:
                            context["opencv_status"] = "skipped_no_image"
                            return context
                        import cv2
                        import numpy as np
                        arr = np.frombuffer(image_bytes, dtype=np.uint8)
                        bgr = cv2.imdecode(arr, cv2.IMREAD_COLOR)
                        if bgr is None:
                            context["opencv_status"] = "error_decode_failed"
                            return context
                        gray = cv2.cvtColor(bgr, cv2.COLOR_BGR2GRAY)
                        denoised = cv2.GaussianBlur(gray, (3, 3), 0)
                        binary = cv2.adaptiveThreshold(
                            denoised, 255,
                            cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
                            cv2.THRESH_BINARY, 15, 8,
                        )
                        context["preprocessed_image"] = binary
                        context["opencv_status"] = "ok"
                        return context
            '''))
        elif cid == "ocr":
            class_blocks.append(dedent('''\
                class OcrComponent(Component):
                    """OCR: Tesseract text extraction (requires Tesseract system binary)."""

                    name = "ocr"

                    def run(self, context: dict) -> dict:
                        preprocessed = context.get("preprocessed_image")
                        if preprocessed is None:
                            context["ocr_status"] = "skipped_no_image"
                            context["ocr_text"] = ""
                            context.setdefault("text", "")
                            return context
                        try:
                            import pytesseract
                            from PIL import Image
                            pil_img = Image.fromarray(preprocessed)
                            text = pytesseract.image_to_string(pil_img, config="--psm 6")
                            context["ocr_text"] = text.strip()
                            context["text"] = text.strip()
                            context["ocr_status"] = "ok"
                        except Exception as exc:
                            context["ocr_status"] = "error"
                            context["ocr_error"] = str(exc)
                            context["ocr_text"] = ""
                            context.setdefault("text", "")
                        return context
            '''))
        elif cid == "text_classifier":
            class_blocks.append(dedent('''\
                class TextClassifierComponent(Component):
                    """Executable: TF-IDF + Logistic Regression text classifier."""

                    name = "text_classifier"

                    def run(self, context: dict) -> dict:
                        import joblib
                        import pathlib
                        model_path = pathlib.Path(__file__).resolve().parent.parent / "models" / "model.joblib"
                        if not model_path.exists():
                            context["text_classifier_status"] = "model_not_trained"
                            context["text_classifier_error"] = (
                                "model.joblib not found. "
                                "Train via POST /api/train?project_id=<id>"
                            )
                            return context
                        model = joblib.load(model_path)
                        text = str(context.get("text", ""))
                        if not text:
                            context["text_classifier_status"] = "skipped_no_text"
                            return context
                        prediction = model.predict([text])[0]
                        probs = model.predict_proba([text])[0]
                        classes = model.classes_.tolist()
                        ranked = sorted(
                            [{"label": c, "confidence": round(float(p), 4)}
                             for c, p in zip(classes, probs)],
                            key=lambda x: x["confidence"],
                            reverse=True,
                        )[:3]
                        context["prediction"] = str(prediction)
                        context["confidence"] = round(float(max(probs)), 4)
                        context["top_predictions"] = ranked
                        context["text_classifier_status"] = "ok"
                        return context
            '''))
        elif executable:
            # Other executable components (future-proofing)
            class_name = "".join(w.title() for w in cid.split("_")) + "Component"
            class_blocks.append(dedent(f'''\
                class {class_name}(Component):
                    """Executable component: {name}."""

                    name = "{cid}"

                    def run(self, context: dict) -> dict:
                        context["{cid}_status"] = "ok"
                        return context
            '''))
        else:
            # Catalog component — honest stub
            class_name = "".join(w.title() for w in cid.split("_")) + "Component"
            class_blocks.append(dedent(f'''\
                class {class_name}(Component):
                    """Catalog component: {name}.
                    Dependencies: {dep_str}
                    Status: not_implemented — requires external configuration.
                    """

                    name = "{cid}"

                    def run(self, context: dict) -> dict:
                        raise NotImplementedError(
                            "{name} is not yet executable in the AIForge MVP. "
                            "It is included in the generated architecture and "
                            "will be activated in a future phase."
                        )
            '''))

    # Build the ordered pipeline instantiation
    _EXPLICIT_CLASS_NAMES: dict[str, str | None] = {
        "opencv": "OpencvComponent",
        "ocr": "OcrComponent",
        "text_classifier": "TextClassifierComponent",
        "fastapi": None,  # serving layer — not in pipeline.py
    }
    component_class_map: dict[str, str] = {}
    for step in steps:
        cid = step["id"]
        class_name = _EXPLICIT_CLASS_NAMES.get(
            cid, "".join(w.title() for w in cid.split("_")) + "Component"
        )
        if class_name:
            component_class_map[cid] = class_name

    pipeline_steps_code = "[\n"
    for cid, cls in component_class_map.items():
        pipeline_steps_code += f"        {cls}(),\n"
    pipeline_steps_code += "    ]"

    return dedent(f'''\
        """
        Generated AI pipeline — produced by AIForge Builder.

        Architecture: {" → ".join(plan.get("pipeline", []))}

        Execution status: {_execution_status(plan)}
        """
        from __future__ import annotations
        from typing import Any


        class Component:
            """Base class for all pipeline components."""

            name: str = "base"

            def run(self, context: dict) -> dict:
                raise NotImplementedError(f"{{self.__class__.__name__}}.run() not implemented")


        # ---------------------------------------------------------------------------
        # Component implementations
        # ---------------------------------------------------------------------------

    ''') + "\n\n".join(class_blocks) + dedent(f'''

        # ---------------------------------------------------------------------------
        # Pipeline
        # ---------------------------------------------------------------------------

        class Pipeline:
            """
            Executes components in order.
            Catalog components that are not yet executable raise NotImplementedError.
            The pipeline catches those and records them in the context as warnings
            rather than crashing, so partial pipelines still return useful results.
            """

            def __init__(self) -> None:
                self.steps: list[Component] = {pipeline_steps_code}

            def run(self, text: str = "", image_bytes: bytes | None = None) -> dict[str, Any]:
                context: dict[str, Any] = {{
                    "text": text,
                    "image_bytes": image_bytes,
                    "pipeline_warnings": [],
                }}
                for component in self.steps:
                    try:
                        context = component.run(context)
                    except NotImplementedError as exc:
                        context["pipeline_warnings"].append(
                            f"{{component.name}}: {{exc}}"
                        )
                return context


        def run_pipeline(text: str = "", image_bytes: bytes | None = None) -> dict[str, Any]:
            """Convenience wrapper — run the full pipeline."""
            return Pipeline().run(text=text, image_bytes=image_bytes)
    ''')


# ---------------------------------------------------------------------------
# server.py
# ---------------------------------------------------------------------------

def _make_server_py(plan: dict[str, Any]) -> str:
    selected = plan.get("selected_components", [])
    has_classifier = "text_classifier" in selected
    has_opencv = "opencv" in selected and REGISTRY.get("opencv", {}).get("executable", False)
    has_ocr = "ocr" in selected and REGISTRY.get("ocr", {}).get("executable", False)
    has_image_pipeline = has_opencv and has_ocr and has_classifier
    non_exec = [
        REGISTRY[c]["name"]
        for c in selected
        if not REGISTRY.get(c, {}).get("executable", False) and c not in ("fastapi",)
    ]

    if has_classifier:
        image_endpoint = ""
        if has_image_pipeline:
            image_endpoint = dedent('''\

                @app.post("/predict-image")
                async def predict_image(file: UploadFile = File(...)):
                    """
                    Accept an image file, run OpenCV preprocessing + OCR + classifier.
                    Returns the extracted text, prediction and confidence.
                    """
                    import cv2
                    import numpy as np
                    import pytesseract
                    from PIL import Image as PILImage

                    image_bytes = await file.read()

                    # 1. OpenCV preprocessing
                    arr = np.frombuffer(image_bytes, dtype=np.uint8)
                    bgr = cv2.imdecode(arr, cv2.IMREAD_COLOR)
                    if bgr is None:
                        raise HTTPException(status_code=400, detail="Could not decode image")
                    gray = cv2.cvtColor(bgr, cv2.COLOR_BGR2GRAY)
                    denoised = cv2.GaussianBlur(gray, (3, 3), 0)
                    binary = cv2.adaptiveThreshold(
                        denoised, 255,
                        cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
                        cv2.THRESH_BINARY, 15, 8,
                    )

                    # 2. OCR
                    try:
                        pil_img = PILImage.fromarray(binary)
                        extracted_text = pytesseract.image_to_string(pil_img, config="--psm 6").strip()
                    except Exception as exc:
                        raise HTTPException(
                            status_code=503,
                            detail=f"OCR failed: {exc}. Ensure Tesseract is installed.",
                        )

                    if not extracted_text:
                        return {
                            "extracted_text": "",
                            "prediction": None,
                            "confidence": None,
                            "top_predictions": [],
                            "note": "No text could be extracted from the image",
                        }

                    # 3. Text classification
                    model = _load_model()
                    if model is None:
                        return {
                            "extracted_text": extracted_text,
                            "prediction": None,
                            "confidence": None,
                            "top_predictions": [],
                            "note": "Model not trained yet",
                        }
                    prediction = model.predict([extracted_text])[0]
                    probs = model.predict_proba([extracted_text])[0]
                    classes = model.classes_.tolist()
                    ranked = sorted(
                        [{"label": c, "confidence": round(float(p), 4)} for c, p in zip(classes, probs)],
                        key=lambda x: x["confidence"],
                        reverse=True,
                    )[:3]
                    return {
                        "extracted_text": extracted_text,
                        "prediction": str(prediction),
                        "confidence": round(float(max(probs)), 4),
                        "top_predictions": ranked,
                    }
            ''')

        file_import = "from fastapi import FastAPI, File, HTTPException, UploadFile" if has_image_pipeline else "from fastapi import FastAPI, HTTPException"
        return dedent(f'''\
            """
            Generated FastAPI service — produced by AIForge Builder.
            Loads model.joblib when available and exposes a real /predict endpoint.
            {f"Also exposes /predict-image for the image → OCR → classifier pipeline." if has_image_pipeline else ""}
            """
            from __future__ import annotations
            import pathlib
            {file_import}
            import joblib

            app = FastAPI(title="Generated AI Service")

            _MODEL_PATH = pathlib.Path(__file__).resolve().parent.parent / "models" / "model.joblib"


            def _load_model():
                if not _MODEL_PATH.exists():
                    return None
                return joblib.load(_MODEL_PATH)


            @app.get("/health")
            def health():
                return {{"status": "ok", "model_ready": _MODEL_PATH.exists()}}


            @app.post("/predict")
            def predict(payload: dict):
                text = str(payload.get("text", ""))
                if not text:
                    raise HTTPException(status_code=400, detail="\'text\' field is required")
                model = _load_model()
                if model is None:
                    raise HTTPException(
                        status_code=503,
                        detail=(
                            "Model not trained yet. "
                            "POST a labeled CSV to /api/train?project_id=<id> first."
                        ),
                    )
                prediction = model.predict([text])[0]
                probs = model.predict_proba([text])[0]
                classes = model.classes_.tolist()
                ranked = sorted(
                    [{{"label": c, "confidence": round(float(p), 4)}} for c, p in zip(classes, probs)],
                    key=lambda x: x["confidence"],
                    reverse=True,
                )[:3]
                return {{
                    "prediction": str(prediction),
                    "confidence": round(float(max(probs)), 4),
                    "top_predictions": ranked,
                }}
        ''') + image_endpoint
    else:
        non_exec_str = ", ".join(non_exec) if non_exec else "unknown"
        return dedent(f'''\
            """
            Generated FastAPI service stub — produced by AIForge Builder.

            NOTE: This pipeline includes components that are not yet executable:
            {non_exec_str}

            The /predict endpoint returns an honest "not_implemented" response.
            Activate the catalog components to enable real inference.
            """
            from fastapi import FastAPI

            app = FastAPI(title="Generated AI Service (catalog pipeline)")


            @app.get("/health")
            def health():
                return {{
                    "status": "ok",
                    "model_ready": False,
                    "execution_status": "partial",
                    "catalog_components": {json.dumps(non_exec)},
                }}


            @app.post("/predict")
            def predict(payload: dict):
                return {{
                    "status": "not_implemented",
                    "catalog_components": {json.dumps(non_exec)},
                    "message": (
                        "This pipeline includes components not yet executable in the "
                        "AIForge MVP: {non_exec_str}. "
                        "The architecture has been generated; activate catalog "
                        "components to enable real inference."
                    ),
                }}
        ''')


# ---------------------------------------------------------------------------
# test_pipeline.py
# ---------------------------------------------------------------------------

def _make_test_pipeline(plan: dict[str, Any]) -> str:
    has_classifier = "text_classifier" in plan.get("selected_components", [])
    if has_classifier:
        return dedent('''\
            """Smoke tests for the generated pipeline."""
            import pytest
            from agent.pipeline import run_pipeline, Pipeline


            def test_pipeline_instantiates():
                p = Pipeline()
                assert len(p.steps) > 0


            def test_run_pipeline_returns_dict():
                result = run_pipeline("test input")
                assert isinstance(result, dict)
                assert "text" in result


            def test_run_pipeline_text_preserved():
                result = run_pipeline("hello world")
                assert result["text"] == "hello world"


            def test_pipeline_without_model_records_status():
                """When model.joblib is absent the classifier records a status rather than crashing."""
                result = run_pipeline("some document text")
                # Either trained (has prediction) or untrained (has status field)
                assert "text_classifier_status" in result or "prediction" in result
        ''')
    else:
        return dedent('''\
            """Smoke tests for the generated pipeline (catalog-only)."""
            from agent.pipeline import run_pipeline, Pipeline


            def test_pipeline_instantiates():
                p = Pipeline()
                assert isinstance(p.steps, list)


            def test_run_pipeline_returns_dict():
                result = run_pipeline("test input")
                assert isinstance(result, dict)
                assert "text" in result


            def test_catalog_components_produce_warnings():
                """Catalog components must not silently pretend to work."""
                result = run_pipeline("test input")
                # Catalog components raise NotImplementedError which is
                # caught and recorded as pipeline_warnings.
                assert "pipeline_warnings" in result
        ''')


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

class BuildResult:
    """Returned by build_project(); carries all information about the build."""

    def __init__(
        self,
        project_id: str,
        project_name: str,
        project_dir: Path,
        plan: dict[str, Any],
        generated_files: list[str],
    ) -> None:
        self.project_id = project_id
        self.project_name = project_name
        self.project_dir = project_dir
        self.plan = plan
        self.generated_files = generated_files
        self.execution_status = _execution_status(plan)

    def to_dict(self) -> dict[str, Any]:
        return {
            "project_id": self.project_id,
            "project_name": self.project_name,
            "project_path": str(self.project_dir),
            "execution_status": self.execution_status,
            "execution_ready": self.plan.get("execution_ready", False),
            "pipeline": self.plan.get("pipeline", []),
            "pipeline_steps": self.plan.get("pipeline_steps", []),
            "selected_components": self.plan.get("selected_components", []),
            "implemented_components": self.plan.get("implemented_components", []),
            "catalog_components": self.plan.get("catalog_components", []),
            "warnings": self.plan.get("warnings", []),
            "generated_files": self.generated_files,
        }


def build_project(project_name: str, spec: str) -> BuildResult:
    """
    Main entry point.

    1. Calls analyze_spec() to get the structured plan.
    2. Validates the plan.
    3. Writes the full project to disk under GENERATED_DIR.
    4. Returns a BuildResult.
    """
    plan = analyze_spec(spec)

    # Validate all component IDs exist in registry
    for cid in plan.get("selected_components", []):
        if cid not in REGISTRY:
            raise ValueError(f"Unknown component id '{cid}' returned by planner")

    project_id = _slugify(project_name) + "-" + uuid.uuid4().hex[:6]
    project_dir = GENERATED_DIR / project_id
    project_dir.mkdir(parents=True, exist_ok=True)

    # Create subdirectories
    (project_dir / "agent").mkdir(exist_ok=True)
    (project_dir / "models").mkdir(exist_ok=True)
    (project_dir / "tests").mkdir(exist_ok=True)

    # Generate all files
    files: dict[str, str] = {
        "README.md": _make_readme(project_name, spec, plan),
        "requirements.txt": _make_requirements(plan),
        "Dockerfile": _make_dockerfile(plan),
        "pipeline.json": _make_pipeline_json(project_id, project_name, spec, plan),
        "agent/__init__.py": '"""Generated Agent Package."""\n',
        "agent/pipeline.py": _make_pipeline_py(plan),
        "agent/runtime.py": (
            '"""Generated Agent Runtime."""\n\n'
            'from agent.pipeline import run_pipeline\n\n\n'
            'class AgentRuntime:\n'
            '    def run(self, text: str = "", image_bytes: bytes | None = None):\n'
            '        return run_pipeline(text=text, image_bytes=image_bytes)\n'
        ),
        "agent/server.py": _make_server_py(plan),
        "tests/test_pipeline.py": _make_test_pipeline(plan),
    }

    for rel, content in files.items():
        path = project_dir / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    # project.json last (needs generated_files list)
    generated_files = list(files.keys()) + ["project.json"]
    project_json = _make_project_json(project_id, project_name, spec, plan, generated_files)
    (project_dir / "project.json").write_text(project_json, encoding="utf-8")

    return BuildResult(
        project_id=project_id,
        project_name=project_name,
        project_dir=project_dir,
        plan=plan,
        generated_files=generated_files,
    )
